volumes:
  portainer_data:
  influx_data:
  influx_config:
  postgres-keycloak-data:
  emqx_data:
  bitswan_backend_production_postgres_data: {}
  bitswan_backend_production_postgres_data_backups: {}
  bitswan-editor-data:

networks:
  bitswan_network:
    external: true
services:
  influxdb:
    image: influxdb:2.0
    restart: always
    container_name: aoc-influxdb
    networks:
      - bitswan_network
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    env_file:
      - envs/influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: aoc-portainer
    networks:
      - bitswan_network
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always

  emqx:
    image: emqx:latest
    container_name: aoc-emqx
    networks:
      - bitswan_network
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    env_file:
      - envs/emqx.env
    volumes:
      - emqx_data:/opt/emqx/data

  keycloak:
    image: bitswan/bitswan-keycloak:2024-9110295480-git-d7a8e49
    networks:
      - bitswan_network
    restart: always
    container_name: aoc-keycloak
    ports:
      - "10000:8080"
    env_file:
      - envs/keycloak.env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    restart: always
    container_name: aoc-keycloak-postgres
    networks:
      - bitswan_network
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    env_file: envs/keycloak-postgres.env

  automation-operation-centre:
    restart: always
    networks:
      - bitswan_network
    depends_on:
      - influxdb
      - bitswan-backend
    image: bitswan/automation-operations-centre:2025-13211829792-git-65ce7c8
    env_file: envs/operations-centre.env
    ports:
      - "3000:3000"

  profile-manager:
    restart: always
    networks:
      - bitswan_network
    image: bitswan/profile-manager:2024-11950867793-git-5ff440c

  bitswan-backend:
    image: bitswan/bitswan-backend:2025-13211829799-git-65ce7c8
    container_name: aoc-bitswan-backend
    depends_on:
      - aoc-bitswan-backend-postgres
    restart: always
    networks:
      - bitswan_network
    env_file:
      - envs/bitswan-backend.env
      - envs/bitswan-backend-postgres.env
    ports:
      - 5000:5000
    command: /start

  bitswan-backend-postgres:
    image: postgres:15-bullseye
    container_name: aoc-bitswan-backend-postgres
    restart: always
    networks:
      - bitswan_network
    volumes:
      - bitswan_backend_production_postgres_data:/var/lib/postgresql/data
      - bitswan_backend_production_postgres_data_backups:/backups
    env_file:
      - envs/bitswan-backend-postgres.env
