name: Keycloak Build and Push

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "keycloak/**"
      - ".github/workflows/keycloak.yml"

jobs:
  build-and-push-staging:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get Year and Commit Hash
        id: varsc
        run: |
          echo "year=$(date +%Y)" >> $GITHUB_ENV
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Image for Staging with Staging and Unique Tags
        id: build
        env:
          IMAGE_TAG: bitswan/bitswan-keycloak
          YEAR: ${{ env.year }}
          COMMIT_HASH: ${{ env.commit_hash }}
          BUILD_NO: ${{ github.run_id }}
        run: |
          UNIQUE_TAG="$IMAGE_TAG:$YEAR-${{ github.run_id }}-git-$COMMIT_HASH"

          # Build and tag with both staging and unique tags
          docker build -t "$IMAGE_TAG:staging" -t "$UNIQUE_TAG" -f ./keycloak/Dockerfile ./keycloak

          # Push the staging and unique tags
          docker push "$IMAGE_TAG:staging"
          docker push "$UNIQUE_TAG"

          # Set the unique tag as an output for use in the production job
          echo "::set-output name=image_tag::$UNIQUE_TAG"
